version: '3'
services:
  travala-promotions:
    container_name: travala-promotions
    hostname: travala-promotions
    image: tomcat:8.5.38-jre8-alpine
    volumes:
      - ./authentications.war:/usr/local/tomcat/webapps/promotions.war
      - /home/ubuntu/travala/env/promotions.conf:/env/promotions/application.properties
      - ./logs/promotion.log:/var/logs/promotions.log
networks:
  default:
    external:
      name: "net-travala"